const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
function makeGame(file){const html=fs.readFileSync(file,'utf8'),geo=html.match(/<script id="world-data" type="application\/json">([\s\S]*?)<\/script>/)[1],code=html.match(/<script>([\s\S]*?)<\/script>/)[1],els=new Map(),registry=new Map();const ctx2d=new Proxy({isPointInPath:()=>false},{get:(t,k)=>t[k]||(()=>{}),set:(t,k,v)=>(t[k]=v,true)});function el(id=''){if(els.has(id))return els.get(id);const e={id,innerHTML:'',textContent:id==='world-data'?geo:'',value:id==='mapmode'?'political':'',hidden:id==='overlay',style:{},dataset:{},classList:{toggle(){}},tagName:'DIV',scrollTop:0,addEventListener(){},setAttribute(){},querySelectorAll(){return[]},getBoundingClientRect(){return{width:1100,height:650,left:0,top:0}},getContext(){return ctx2d},insertAdjacentHTML(_,s){this.innerHTML=s+this.innerHTML},focus(){},click(){},scrollIntoView(){},setPointerCapture(){}};els.set(id,e);return e;}
const scope={console,performance,structuredClone,TextEncoder,Blob,URL,innerWidth:1440,devicePixelRatio:1,Path2D:class{moveTo(){}lineTo(){}closePath(){}},ResizeObserver:class{observe(){}},requestAnimationFrame:()=>1,setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},AbortController,localStorage:{getItem:()=>null,setItem(){}},document:{hidden:false,modelContext:{registerTool(t){registry.set(t.name,t)}},activeElement:el('body'),getElementById:el,querySelectorAll:()=>[],addEventListener(){},createElement:()=>el('created')},window:{addEventListener(){}}};vm.createContext(scope);vm.runInContext(code,scope);return{run:c=>vm.runInContext(c,scope),scope,registry,els,html};}
const v4=makeGame('build/v4.html'),{run}=v4;
assert.equal(run('S.version'),4);assert.equal(run('S.nations.length'),175);assert.equal(run('Object.keys(PRESETS).length'),14);assert.equal(run('S.nations.reduce((a,n)=>a+n.cities.length,0)'),525);
for(const view of ['overview','cities','parties','policies','economy','diplomacy','military','history','settings'])run(`setView('${view}');renderPanel()`);
run("view='policies';for(const tab of ['reforms','programs','taxation','ideologies']){subview=tab;renderPanel()}for(const pr of PROGRAMS){activeProgram=pr.key;subview='program';renderPanel()}showGuide();closeModal();selected='ARG';view='diplomacy';renderPanel();drawMap()");
// Each preset remains a full, finite policy bundle and yields a real map color.
assert(run('Object.values(PRESETS).every(p=>POLICY.filter(x=>!["liberties","institutions"].includes(x.key)).every(x=>Number.isFinite(p[x.key])&&p[x.key]>=x.min&&p[x.key]<=x.max))'));
run("newGame();renderTick=()=>{};S.options.shocks=false;S.options.ai=false;S.options.infiniteCapital=true;");
// Correct marginal brackets; taxes do not double-count the overall model.
assert(Math.abs(run("personalTax(4,{...player().policies,taxMode:'progressive',taxLow:0,taxMiddle:10,taxUpper:20,taxTop:40})")-.8)<1e-9);
assert(Math.abs(run("taxation({...player().policies,taxMode:'simple'}).total-player().policies.tax"))<1e-9);
// City spending is spread across the exact construction duration, charged once, and bounded.
run("const c=player().cities[0];startCityProject(player().id,c.id,'hospital');const testProject=structuredClone(c.queue[0]);const initialLevel=c.levels.hospital;const baseline=JSON.stringify(S);prepareV4Month();const firstBudget=player().citySpend;for(let i=0;i<testProject.duration-1;i++)simulateMonth();");
assert.equal(run('player().cities[0].levels.hospital'),0);assert(run('player().citySpend>0'));assert(Math.abs(run('firstBudget*player().history[0]/1200')-run('testProject.cost/testProject.duration'))<1e-8);
run('simulateMonth()');assert.equal(run('player().cities[0].levels.hospital'),1);assert.equal(run('player().cities[0].queue.length'),0);run('simulateMonth()');assert.equal(run('player().citySpend'),0);assert(run('player().cityUpkeep>0'));
run("startCityProject(player().id,c.id,'housing');startCityProject(player().id,c.id,'water')");assert.equal(run("startCityProject(player().id,c.id,'solar')"),false);run('cancelCityProject(c.id,0)');assert.equal(run('player().cities[0].queue.length'),1);
// Diplomacy locks repeated actions, types have distinct effects, and sanctions are directional.
run("newGame();S.options.infiniteCapital=true;S.options.shocks=false;S.options.ai=false;selected='ARG';setRelation('BRA','ARG',70);player().policies.services=12;current().policies.services=12;player().policies.climate=70;current().policies.climate=70;diplomacy('outreach');const afterOutreach=relation('BRA','ARG');diplomacy('outreach')");assert.equal(run("relation('BRA','ARG')"),run('afterOutreach'));
run("for(const type of ['trade','embassy','research','climate','nonaggression','defense'])diplomacy(type)");assert.equal(run('S.agreements.length'),6);run("diplomacy('trade')");assert.equal(run('S.agreements.length'),6);run('prepareV4Month()');assert(run('player().pactResearch>0&&player().pactClimate>0&&player().pactDefense>0'));run('declareWar()');assert.equal(run('player().war'),null);
run("diplomacy('sanction');S.player='ARG';selected='BRA';diplomacy('sanction')");assert.equal(run('S.embargoes.length'),2);run("diplomacy('sanction')");assert.equal(run('S.embargoes.length'),1);assert.equal(run('S.embargoes[0].from'),'BRA');run('prepareV4Month()');assert.equal(run('player().pactResearch'),0);
run("S.player='BRA';selected='ARG';diplomacy('sanction');withdrawPact('nonaggression');withdrawPact('defense');declareWar()");assert.equal(run('player().war.target'),'ARG');assert.equal(run('S.agreements.length'),0);run('peace()');assert.equal(run('player().war'),null);
// Election seats total exactly 100, campaigns and elections have cooldowns.
run("newGame();S.options.infiniteCapital=true;player().policies.institutions=90;politicalAction('campaign',3);const boost=player().politics.boost[3];politicalAction('campaign',3)");assert.equal(run('player().politics.boost[3]'),run('boost'));
run('player().election=1;simulateMonth()');assert.equal(run('player().election'),48);assert.equal(run('player().politics.seats.reduce((a,b)=>a+b,0)'),100);assert(run('player().politics.coalition.includes(player().politics.leader)'));
// Forgiving interest is lower than standard; no consecutive monthly forced debt penalties.
run("newGame();player().debt=player().gdp*7;S.options.forgivingDebt=false;const normalRate=fiscal(player()).interest;S.options.forgivingDebt=true;const forgivingRate=fiscal(player()).interest");assert(run('forgivingRate<normalRate'));run('for(let i=0;i<11;i++)handleDebtV4(player())');assert.equal(run('player().crisisGrace'),0);const before=run('player().debt');run('handleDebtV4(player())');assert.equal(run('player().debt'),before*.75);assert.equal(run('player().crisisGrace'),48);run('player().debt=player().gdp*8;const debtProtected=player().debt;for(let i=0;i<30;i++)handleDebtV4(player())');assert.equal(run('player().debt'),run('debtProtected'));
// Migrate actual V3 save with projects, fiscal state, old treaties and tax settings preserved.
const v3=makeGame('src/base/sovereign-v3.html');const v3save=v3.run("S.month=15;S.treaties=['ARG:BRA'];S.sanctions=['BRA:USA'];player().policies.taxMode='progressive';JSON.stringify(S)");v4.scope.legacyJSON=v3save;run('loadSave(legacyJSON)');assert.equal(run('S.version'),4);assert.equal(run('S.month'),15);assert.equal(run('player().policies.taxMode'),'progressive');assert.equal(run('S.agreements.length'),1);assert.equal(run('S.embargoes[0].from'),'BRA');run('validSave(JSON.parse(JSON.stringify(S)))');
// Earlier saves migrate as well, without altering the original artifact.
const v1=makeGame('src/base/sovereign-v1.html');v4.scope.v1JSON=v1.run('JSON.stringify(S)');run('loadSave(v1JSON);validSave(JSON.parse(JSON.stringify(S)))');assert.equal(run('S.version'),4);
// Fifty years of AI, city completions, elections and agreements must remain finite and loadable.
run('newGame();for(let i=0;i<600;i++)simulateMonth();validSave(JSON.parse(JSON.stringify(S)))');
assert(run('S.nations.every(n=>Number.isFinite(n.gdp)&&n.gdp>0&&Number.isFinite(n.debt)&&n.debt>=0&&n.history.length<=120&&n.cities.every(c=>c.queue.length<=2)&&n.politics.seats.reduce((a,b)=>a+b,0)===100)'));
// Invalid imported data must fail atomically.
assert.throws(()=>run('let broken=JSON.parse(JSON.stringify(S));broken.nations[0].cities[0].queue=[{type:"missing",duration:12,remaining:4,cost:1}];validSave(broken)'));
assert.throws(()=>run('let broken2=JSON.parse(JSON.stringify(S));broken2.nations[0].politics.seats[0]+=1;validSave(broken2)'));
assert.throws(()=>run('let broken3=JSON.parse(JSON.stringify(S));broken3.agreements.push({a:"BRA",b:"ARG",type:"unknown",expires:S.month+1});validSave(broken3)'));
assert.throws(()=>run('let broken4=JSON.parse(JSON.stringify(S));broken4.nations[0].cities[0].name="<img>";validSave(broken4)'));
assert.throws(()=>run('let broken5=JSON.parse(JSON.stringify(S));broken5.nations[0].cities[0].levels.missing=1;validSave(broken5)'));
const api=v4.registry.get('advance_simulation');const month=run('S.month');api.execute({months:2});assert.equal(run('S.month'),month+2);assert.throws(()=>api.execute({months:-1}));
console.log(JSON.stringify({status:'PASS',nations:run('S.nations.length'),cities:525,ideologies:14,policies:run('POLICY.length'),programs:run('PROGRAMS.length'),fileBytes:Buffer.byteLength(v4.html),lastTickMs:run('perf'),checks:['all panels and programs render','marginal taxation','city financing and completion','construction slot limits','typed diplomacy and cooldowns','directional sanctions','war pact restrictions','election and coalition integrity','forgiving debt and crisis grace','actual V3 save migration','50-year simulation','invalid save rejection','WebMCP shared actions']},null,2));
