// SOVEREIGN V4 — Local cities, parliamentary politics and diplomatic agreements.
// All parties, municipal statistics, coefficients and acceptance rules are scenario abstractions.
const V4_POLICIES=[
{key:'antiCorruption',name:'Transparent procurement & anti-corruption',min:0,max:100,step:5,unit:'/ 100',group:'Government reform',desc:'Oversight strengthens administrative capacity gradually. Costs up to 0.6% of GDP each year.'},
{key:'decentralization',name:'Local government autonomy',min:0,max:100,step:5,unit:'/ 100',desc:'Local discretion accelerates municipal delivery; coordination costs up to 0.3% of GDP.'},
{key:'business',name:'Business licensing reform',min:0,max:100,step:5,unit:'/ 100',desc:'Simpler registration supports investment without removing labor or environmental protections.'},
{key:'research',name:'Public research & innovation',min:0,max:5,step:.25,unit:'% GDP',group:'Opportunity & security',desc:'A recurring research budget builds knowledge and productive capacity over time.'},
{key:'minimumWage',name:'Minimum-wage ambition',min:0,max:100,step:5,unit:'/ 100',desc:'Higher wage floors support incomes. Very high floors can reduce hiring in this simplified model.'},
{key:'immigration',name:'Immigration & integration access',min:0,max:100,step:5,unit:'/ 100',desc:'More open access expands the workforce; new residents also need housing and public services.'},
{key:'pension',name:'Public pension supplement',min:0,max:5,step:.25,unit:'% GDP',desc:'Additional retirement income lowers measured inequality and raises recurring spending.'},
{key:'foodSecurity',name:'Food security & farm resilience',min:0,max:3,step:.25,unit:'% GDP',desc:'Agricultural resilience reduces supply-shock exposure and supports rural living standards.'}
];
const V4_DEFAULTS={antiCorruption:45,decentralization:45,business:50,research:.5,minimumWage:45,immigration:50,pension:0,foodSecurity:0};
POLICY.push(...V4_POLICIES);Object.assign(EXTRA_DEFAULTS,V4_DEFAULTS);
for(const p of Object.values(PRESETS))Object.assign(p,V4_DEFAULTS);
const MORE_IDEOLOGIES={
'Green politics':{base:'Social democratic',desc:'Ecological transition, public transport, redistribution and local democracy.',tax:43,welfare:14,climate:100,investment:5,ownership:40,trade:65,foodSecurity:2,decentralization:80},
'Libertarian':{base:'Market liberal',desc:'Minimal taxation and state ownership, open markets and voluntary exchange.',tax:16,services:5,welfare:1,labor:10,ownership:0,trade:100,business:95},
'National conservative':{base:'Conservative',desc:'Domestic industry, selective trade, stronger defense and family support.',tax:31,trade:35,defense:5,labor:50,ownership:35,immigration:20,industrial:3},
'Christian democratic':{base:'Social liberal',desc:'A social market economy, family support, social insurance and private enterprise.',tax:36,labor:65,welfare:12,ownership:25,childcare:2,pension:1.5},
'Market socialist':{base:'Democratic socialist',desc:'Worker bargaining and social ownership alongside competitive markets.',tax:42,ownership:70,trade:85,labor:90,investment:5,business:65},
'Technocratic centrist':{base:'Social liberal',desc:'Administrative competence, research, infrastructure and pragmatic mixed markets.',tax:34,labor:50,ownership:30,research:3,antiCorruption:90,business:80},
'Agrarian':{base:'Conservative',desc:'Rural services, farm resilience, decentralized institutions and small enterprise.',tax:30,foodSecurity:3,ruralInvest:4,trade:50,decentralization:85,labor:60},
'Communist':{base:'Democratic socialist',desc:'Extensive public ownership, strong redistribution and planned investment.',tax:52,ownership:95,trade:35,labor:95,welfare:20,investment:7,industrial:4}
};
for(const[name,p]of Object.entries(MORE_IDEOLOGIES)){const{base,...values}=p;PRESETS[name]={...PRESETS[base],...values};}
PROGRAMS.push(
{key:'governance',name:'Clean government',tag:'Government reform',blurb:'Professional institutions and transparent purchasing improve the state’s ability to deliver.',keys:['antiCorruption','institutions','decentralization','business'],stage:{antiCorruption:85,institutions:80,decentralization:65,business:75},stageNote:'Stages independent oversight, stronger safeguards and simpler business registration.'},
{key:'innovation',name:'Research economy',tag:'Opportunity',blurb:'Knowledge, skills and investment support a productive economy over time.',keys:['research','services','business','investment'],stage:{research:3,services:14,business:80,investment:5},stageNote:'Stages research at 3% of GDP, education and simpler business licensing.'},
{key:'security',name:'Household security',tag:'Social policy',blurb:'Retirement income, wage protection and a more resilient food supply.',keys:['pension','minimumWage','foodSecurity','ruralInvest'],stage:{pension:2,minimumWage:65,foodSecurity:2,ruralInvest:2},stageNote:'Stages pension support, wage-floor reform and food resilience.'}
);
Object.assign(RELIEF.terms,{cost:6,cooldown:9});Object.assign(RELIEF.refinance,{cost:10,cooldown:18});Object.assign(RELIEF.restructure,{cost:18,cooldown:36});
const CITY_NAMES={USA:['New York','Los Angeles','Chicago'],CAN:['Toronto','Montreal','Vancouver'],MEX:['Mexico City','Monterrey','Guadalajara'],BRA:['São Paulo','Rio de Janeiro','Brasília'],ARG:['Buenos Aires','Córdoba','Rosario'],CHL:['Santiago','Valparaíso','Concepción'],COL:['Bogotá','Medellín','Cali'],PER:['Lima','Arequipa','Trujillo'],VEN:['Caracas','Maracaibo','Valencia'],GBR:['London','Manchester','Birmingham'],FRA:['Paris','Lyon','Marseille'],DEU:['Berlin','Hamburg','Munich'],ESP:['Madrid','Barcelona','Valencia'],PRT:['Lisbon','Porto','Coimbra'],ITA:['Rome','Milan','Naples'],NLD:['Amsterdam','Rotterdam','Utrecht'],POL:['Warsaw','Kraków','Gdańsk'],NOR:['Oslo','Bergen','Trondheim'],SWE:['Stockholm','Gothenburg','Malmö'],FIN:['Helsinki','Tampere','Turku'],UKR:['Kyiv','Lviv','Odesa'],RUS:['Moscow','Saint Petersburg','Novosibirsk'],TUR:['Istanbul','Ankara','İzmir'],CHN:['Shanghai','Beijing','Shenzhen'],IND:['Mumbai','Delhi','Bengaluru'],PAK:['Karachi','Lahore','Islamabad'],BGD:['Dhaka','Chattogram','Khulna'],JPN:['Tokyo','Osaka','Nagoya'],KOR:['Seoul','Busan','Incheon'],PRK:['Pyongyang','Hamhung','Chongjin'],IDN:['Jakarta','Surabaya','Bandung'],THA:['Bangkok','Chiang Mai','Khon Kaen'],VNM:['Hanoi','Ho Chi Minh City','Da Nang'],MYS:['Kuala Lumpur','George Town','Johor Bahru'],PHL:['Manila','Cebu','Davao'],AUS:['Sydney','Melbourne','Brisbane'],NZL:['Auckland','Wellington','Christchurch'],SAU:['Riyadh','Jeddah','Dammam'],IRN:['Tehran','Isfahan','Shiraz'],IRQ:['Baghdad','Basra','Erbil'],ISR:['Tel Aviv','Haifa','Beersheba'],ARE:['Dubai','Abu Dhabi','Sharjah'],EGY:['Cairo','Alexandria','Giza'],ZAF:['Johannesburg','Cape Town','Durban'],NGA:['Lagos','Abuja','Kano'],ETH:['Addis Ababa','Dire Dawa','Adama'],KEN:['Nairobi','Mombasa','Kisumu'],DZA:['Algiers','Oran','Constantine'],MAR:['Casablanca','Rabat','Marrakesh'],COD:['Kinshasa','Lubumbashi','Goma'],TZA:['Dar es Salaam','Dodoma','Arusha'],KAZ:['Almaty','Astana','Shymkent']};
const PROJECTS={
 housing:{name:'Affordable housing district',cost:1.2,months:24,desc:'More affordable homes and lower housing pressure.',effects:{housing:12,quality:3}},
 metro:{name:'Transit corridor',cost:1.8,months:30,desc:'More reliable mobility, cleaner travel and access to jobs.',effects:{mobility:15,quality:3}},
 hospital:{name:'Hospital & primary-care network',cost:.9,months:18,desc:'Improves local health and service access.',effects:{health:14,quality:4}},
 university:{name:'University & technical college',cost:1,months:24,desc:'Builds skills and supports national innovation.',effects:{education:14,jobs:4}},
 industry:{name:'Industrial & logistics park',cost:1.4,months:20,desc:'Adds productive sites and local jobs; consumes more energy.',effects:{jobs:15,quality:-2}},
 solar:{name:'Clean power & grid upgrades',cost:1,months:18,desc:'Cleaner, more resilient local electricity.',effects:{energy:16,quality:3}},
 water:{name:'Water & sanitation network',cost:.7,months:12,desc:'Improves health and conditions in underserved districts.',effects:{health:7,housing:5,quality:6}},
 fiber:{name:'Broadband & digital services',cost:.6,months:12,desc:'Better business access, learning and public services.',effects:{education:6,jobs:8}}
};
const PARTY_DEFS=[
{id:'liberal',name:'Civic Liberal Party',ideology:'Social liberal',color:'#83baca'},
{id:'social',name:'Labor & Solidarity',ideology:'Social democratic',color:'#d78183'},
{id:'conservative',name:'Conservative Union',ideology:'Conservative',color:'#8a9acc'},
{id:'green',name:'Green Alliance',ideology:'Green politics',color:'#8bbc83'},
{id:'socialist',name:'Workers’ Cooperative Party',ideology:'Market socialist',color:'#c788a5'},
{id:'national',name:'National Renewal',ideology:'National conservative',color:'#c3a478'},
{id:'liberty',name:'Liberty Movement',ideology:'Libertarian',color:'#dbce79'},
{id:'reform',name:'Pragmatic Reform Party',ideology:'Technocratic centrist',color:'#91b4ac'}
];
const DIPLOMACY={
 outreach:{name:'Diplomatic outreach',cost:6,months:6,min:-100,desc:'Relations +10. A six-month cooldown prevents repeated lobbying.'},
 embassy:{name:'Open reciprocal embassies',cost:10,months:120,min:0,desc:'Relations slowly improve while embassies remain open.'},
 trade:{name:'Free-trade agreement',cost:14,months:60,min:25,desc:'More market access. Requires trade openness of at least 40 on both sides.'},
 research:{name:'Research exchange',cost:12,months:48,min:35,desc:'Improves human capital over time. Both countries need public services of at least 8% GDP.'},
 climate:{name:'Clean-energy partnership',cost:12,months:48,min:25,desc:'Accelerates clean-energy deployment. Both sides need transition effort of at least 40.'},
 nonaggression:{name:'Non-aggression pact',cost:10,months:48,min:15,desc:'Improves stability. War requires withdrawing first, with a reputation cost.'},
 defense:{name:'Defensive cooperation',cost:20,months:60,min:55,desc:'Joint training improves readiness and equipment effectiveness. Does not automatically declare war.'},
 aid:{name:'Development assistance',cost:8,months:12,min:-25,desc:'Send a one-time grant. Improves relations and recipient infrastructure; the donor finances the grant.'},
 summit:{name:'Hold a bilateral summit',cost:10,months:12,min:-10,desc:'Relations +8 and reputation +2. One summit per year with this partner.'},
 mediate:{name:'Mediate a ceasefire',cost:18,months:12,min:10,desc:'Ends this partner’s war when the other belligerent also has nonnegative relations with you.'},
 sanction:{name:'Impose targeted sanctions',cost:10,months:6,min:-100,desc:'Restricts commerce and damages relations. Only the issuer can lift its sanctions.'}
};
const PACT_TYPES=['embassy','trade','research','climate','nonaggression','defense'];
let activeCity=0;
function v4Cities(n){return(CITY_NAMES[n.id]||['Capital district','Regional center','Growth district']).map((name,i)=>({id:n.id+'-'+i,name,share:[.22,.16,.12][i],levels:Object.fromEntries(Object.keys(PROJECTS).map(k=>[k,0])),queue:[]}));}
function seatsFor(polls){const seats=polls.map(Math.floor);let left=100-seats.reduce((a,b)=>a+b,0);const order=polls.map((v,i)=>({i,f:v-Math.floor(v)})).sort((a,b)=>b.f-a.f||a.i-b.i);for(let i=0;i<left;i++)seats[order[i%order.length].i]++;return seats;}
function partyDistance(a,b){const keys=['tax','welfare','ownership','labor','trade','climate'];return keys.reduce((v,k)=>v+Math.abs(a[k]-b[k])/(POLICY.find(p=>p.key===k).max-POLICY.find(p=>p.key===k).min),0)/keys.length;}
function initialPolitics(n){const weights=PARTY_DEFS.map(p=>Math.exp(-partyDistance(n.policies,PRESETS[p.ideology])*5)),total=weights.reduce((a,b)=>a+b,0),polls=weights.map(v=>v/total*100),seats=seatsFor(polls),leader=seats.indexOf(Math.max(...seats));return{polls,seats,leader,coalition:[leader],boost:Array(8).fill(0),campaignCooldown:0,snapCooldown:0,preference:Object.fromEntries(['tax','welfare','ownership','labor','trade','climate'].map(k=>[k,n.policies[k]]))};}
function ensureV4(n){Object.assign(n,{cities:v4Cities(n),politics:initialPolitics(n),reputation:50,crisisMonths:0,crisisGrace:0,citySpend:0,cityUpkeep:0,cityGrowth:0,pactGrowth:0,pactResearch:0,pactClimate:0,pactDefense:0});for(const key of ['policies','targets'])n[key]={...V4_DEFAULTS,...n[key]};}
const originalNewGame=newGame;
newGame=function(){originalNewGame();S.version=4;S.agreements=[];S.embargoes=[];S.diplomaticCooldowns={};S.options.forgivingDebt=true;for(const n of S.nations)ensureV4(n);activeCity=0;addEvent('A more detailed world','Manage cities, negotiate specialized agreements and form a governing coalition. V3 saves can be imported.','dispatch');};
function cityMetrics(n,c){const m={housing:clamp(52-n.slums*.4,10,80),mobility:n.infra*.65,health:n.human*.7,education:n.human*.7,jobs:50,energy:n.clean*.7,quality:clamp(60-n.slums*.5,10,90)};for(const[k,level]of Object.entries(c.levels))for(const[field,amount]of Object.entries(PROJECTS[k].effects))m[field]+=level*amount;for(const k of Object.keys(m))m[k]=clamp(m[k],0,100);return m;}
function prepareV4Month(){syncDiplomacy();for(const n of S.nations){n.citySpend=0;n.cityUpkeep=0;n.cityGrowth=0;n.pactGrowth=0;n.pactResearch=0;n.pactClimate=0;n.pactDefense=0;for(const c of n.cities){for(const q of c.queue)n.citySpend+=q.cost/q.duration*12/n.gdp*100;const levels=Object.values(c.levels).reduce((a,b)=>a+b,0);n.cityUpkeep+=levels*c.share*.018;n.cityGrowth+=c.share*(c.levels.industry*.07+c.levels.university*.04+c.levels.fiber*.04+c.levels.metro*.035);}}for(const pact of S.agreements){if(pact.expires<=S.month)continue;const a=nation(pact.a),b=nation(pact.b);if(a.war?.target===b.id||S.sanctions.includes(pair(a.id,b.id)))continue;for(const n of [a,b]){if(pact.type==='research')n.pactResearch=clamp(n.pactResearch+.04,0,.16);if(pact.type==='climate')n.pactClimate=clamp(n.pactClimate+.07,0,.28);if(pact.type==='defense')n.pactDefense=clamp(n.pactDefense+3,0,9);}}}
function tickCities(n){for(const c of n.cities){const done=[];for(const q of c.queue){q.remaining--;if(q.remaining<=0){c.levels[q.type]++;done.push(q);if(n.id===S.player)addEvent('City project completed',c.name+': '+PROJECTS[q.type].name+' is now operating.','development');}}c.queue=c.queue.filter(q=>!done.includes(q));const m=cityMetrics(n,c);n.human+=(m.education+m.health-100)*c.share*.0005;n.clean+=c.levels.solar*c.share*.015;n.rentBurden=clamp(n.rentBurden-c.levels.housing*c.share*.01,8,65);}if(S.options.ai&&n.id!==S.player&&S.month%12===0){const c=n.cities[(S.month/12)%3|0],keys=Object.keys(PROJECTS),key=keys[(S.month/12+n.id.charCodeAt(0))%keys.length|0];startCityProject(n.id,c.id,key,true);}}
function startCityProject(nid,cid,type,ai=false){const n=nation(nid),c=n?.cities.find(c=>c.id===cid),p=PROJECTS[type];if(!n||!c||!p||(!ai&&n.id!==S.player))return false;if(c.queue.length>=2||c.levels[type]+c.queue.filter(q=>q.type===type).length>=5){if(!ai)toast('This city has two active projects, or this development is already at its level limit.');return false;}if(!canSpend(n,6)){if(!ai)toast('This project needs 6 political capital.');return false;}spendCapital(n,6);const duration=Math.max(6,Math.ceil(p.months*(1.1-n.policies.decentralization*.002)));c.queue.push({type,duration,remaining:duration,cost:n.gdp*c.share*p.cost/100});if(!ai){addEvent('City development approved',c.name+' begins '+p.name.toLowerCase()+'. Spending is distributed across '+duration+' months.','development');renderPanel();renderStats();toast('Construction approved. Advance time to build.');}return true;}
function cancelCityProject(cid,index){const c=player().cities.find(c=>c.id===cid);if(!c||!Number.isInteger(index)||!c.queue[index])return;const q=c.queue.splice(index,1)[0];addEvent('Project cancelled',c.name+': '+PROJECTS[q.type].name+'. Completed spending is not refunded; future payments stop.','development');renderPanel();toast('Project cancelled; future spending stopped.');}
function coalitionSeats(n){return n.politics.coalition.reduce((v,i)=>v+n.politics.seats[i],0);}
function tickPolitics(n){const p=n.politics;if(p.campaignCooldown>0)p.campaignCooldown--;if(p.snapCooldown>0)p.snapCooldown--;const raw=PARTY_DEFS.map((d,i)=>Math.exp(-partyDistance(p.preference,PRESETS[d.ideology])*5)*(i===p.leader?clamp(n.approval/55,.45,1.6):1)+p.boost[i]*.02),total=raw.reduce((a,b)=>a+b,0);for(let i=0;i<8;i++){p.polls[i]+=(raw[i]/total*100-p.polls[i])/12;p.boost[i]*=.96;}const sum=p.polls.reduce((a,b)=>a+b,0);p.polls=p.polls.map(v=>v/sum*100);if(n.policies.institutions>=60){n.election--;if(n.election<=0)holdElection(n);} }
function holdElection(n){const p=n.politics;p.seats=seatsFor(p.polls);p.leader=p.seats.indexOf(Math.max(...p.seats));p.coalition=[p.leader];const other=PARTY_DEFS.map((d,i)=>({i,distance:partyDistance(PRESETS[d.ideology],PRESETS[PARTY_DEFS[p.leader].ideology])})).filter(x=>x.i!==p.leader).sort((a,b)=>a.distance-b.distance);for(const q of other){if(coalitionSeats(n)>50)break;if(q.distance<.42)p.coalition.push(q.i);}n.election=48;p.snapCooldown=24;n.capital=clamp(n.capital+12,0,100);if(n.id===S.player)addEvent('Election results',PARTY_DEFS[p.leader].name+' leads the new cabinet with '+coalitionSeats(n)+' of 100 seats in its coalition. Policy changes remain your choice.','politics');}
function politicalAction(action,id){const n=current(),p=n.politics;if(n.id!==S.player)return;if(action==='campaign'){if(!Number.isInteger(id)||!PARTY_DEFS[id])return;if(p.campaignCooldown||!canSpend(n,8)){toast('Campaigns require 8 capital and a six-month interval.');return;}spendCapital(n,8);p.boost[id]+=15;p.campaignCooldown=6;toast('Campaign launched. Support changes over the coming months.');}if(action==='lead'){if(!PARTY_DEFS[id])return;p.leader=id;p.coalition=[id];toast('Cabinet leadership changed. Build a coalition for easier reforms.');}if(action==='coalition'){if(!PARTY_DEFS[id]||id===p.leader)return;if(p.coalition.includes(id))p.coalition=p.coalition.filter(i=>i!==id);else{if(partyDistance(PRESETS[PARTY_DEFS[id].ideology],PRESETS[PARTY_DEFS[p.leader].ideology])>.5){toast('This party declines: its platform is too distant from the cabinet.');return;}p.coalition.push(id);}}if(action==='election'){if(n.policies.institutions<60||p.snapCooldown||!canSpend(n,15)){toast('Snap elections need competitive institutions, 15 capital, and no election cooldown.');return;}spendCapital(n,15);holdElection(n);}if(action==='platform'){if(coalitionSeats(n)===0){toast('Invite parties with elected seats before staging a coalition platform.');return;}draft={...n.targets};for(const x of POLICY){if(['liberties','institutions'].includes(x.key)||x.tax)continue;draft[x.key]=p.coalition.reduce((v,i)=>v+PRESETS[PARTY_DEFS[i].ideology][x.key]*p.seats[i],0)/Math.max(1,coalitionSeats(n));}view='policies';subview='reforms';dirty=true;toast('Coalition platform staged. Review and enact it.');}render();}
function diplomaticLock(a,b,action){return Math.max(0,(S.diplomaticCooldowns[(action==='sanction'?a+':'+b:pair(a,b))+':'+action]||0)-S.month);}
function lockDiplomacy(a,b,action,months){S.diplomaticCooldowns[(action==='sanction'?a+':'+b:pair(a,b))+':'+action]=S.month+months;}
function agreement(a,b,type){return S.agreements.find(p=>p.type===type&&pair(p.a,p.b)===pair(a,b)&&p.expires>S.month);}
function syncDiplomacy(){S.treaties=[...new Set(S.agreements.filter(p=>p.type==='trade'&&p.expires>S.month).map(p=>pair(p.a,p.b)))];S.sanctions=[...new Set(S.embargoes.map(e=>pair(e.from,e.to)))];}
function diplomacyProblem(a,b,type){const d=DIPLOMACY[type];if(!d)return 'Unknown action.';if(a.id===b.id)return 'Select another nation.';if(type==='sanction'&&S.embargoes.some(e=>e.from===a.id&&e.to===b.id))return '';if(!canSpend(a,d.cost))return 'Requires '+d.cost+' political capital.';const wait=diplomaticLock(a.id,b.id,type);if(wait)return 'Available in '+wait+' months.';if(type!=='sanction'&&a.war?.target===b.id)return 'Negotiate peace before normal diplomacy.';if(PACT_TYPES.includes(type)&&agreement(a.id,b.id,type))return 'Already active.';if(PACT_TYPES.includes(type)&&S.sanctions.includes(pair(a.id,b.id)))return 'Resolve sanctions before signing agreements.';const requirement=d.min+(PACT_TYPES.includes(type)?Math.max(0,40-a.reputation)*.25:0);if(relation(a.id,b.id)<requirement)return 'Needs relations of at least '+Math.ceil(requirement)+' (including reputation).';if(type==='trade'&&Math.min(a.policies.trade,b.policies.trade)<40)return 'Both sides need trade openness of 40.';if(type==='research'&&Math.min(a.policies.services,b.policies.services)<8)return 'Both sides need services spending of 8% GDP.';if(type==='climate'&&Math.min(a.policies.climate,b.policies.climate)<40)return 'Both sides need transition effort of 40.';if(type==='mediate'&&(!b.war||b.war.target===a.id||relation(a.id,b.war.target)<0))return 'Partner must be in a third-party war; both belligerents must accept your role.';return '';}
diplomacy=function(type){const a=player(),b=current(),d=DIPLOMACY[type];if(!d||a.id===b.id)return;const ownSanction=S.embargoes.find(e=>e.from===a.id&&e.to===b.id);if(type==='sanction'&&ownSanction){S.embargoes=S.embargoes.filter(e=>e!==ownSanction);setRelation(a.id,b.id,relation(a.id,b.id)+8);syncDiplomacy();render();toast('Your sanctions have been lifted.');return;}const issue=diplomacyProblem(a,b,type);if(issue){toast(issue);return;}spendCapital(a,d.cost);lockDiplomacy(a.id,b.id,type,PACT_TYPES.includes(type)?12:d.months);
 if(PACT_TYPES.includes(type)){S.agreements.push({a:a.id,b:b.id,type,expires:S.month+d.months});setRelation(a.id,b.id,relation(a.id,b.id)+3);}
 if(type==='outreach')setRelation(a.id,b.id,relation(a.id,b.id)+10);
 if(type==='summit'){setRelation(a.id,b.id,relation(a.id,b.id)+8);a.reputation=clamp(a.reputation+2,0,100);}
 if(type==='aid'){const grant=Math.min(a.gdp*.002,b.gdp*.005);a.debt+=grant;b.debt=Math.max(0,b.debt-grant);b.infra=clamp(b.infra+1,0,100);setRelation(a.id,b.id,relation(a.id,b.id)+12);a.reputation=clamp(a.reputation+1,0,100);}
 if(type==='mediate'){const c=nation(b.war.target);b.war=null;c.war=null;setRelation(b.id,c.id,-25);a.reputation=clamp(a.reputation+5,0,100);addEvent('Mediated ceasefire',a.name+' helped '+b.name+' and '+c.name+' end their conflict.','diplomacy');}
 if(type==='sanction'){S.embargoes.push({from:a.id,to:b.id});S.agreements=S.agreements.filter(p=>pair(p.a,p.b)!==pair(a.id,b.id)||!['trade','research'].includes(p.type));setRelation(a.id,b.id,relation(a.id,b.id)-25);}
 syncDiplomacy();addEvent(d.name,a.name+' and '+b.name+': diplomatic action completed.','diplomacy');render();toast(d.name+' completed.');};
function withdrawPact(type){const a=player(),b=current(),p=agreement(a.id,b.id,type);if(!p)return;S.agreements=S.agreements.filter(x=>x!==p);setRelation(a.id,b.id,relation(a.id,b.id)-10);a.reputation=clamp(a.reputation-4,0,100);lockDiplomacy(a.id,b.id,type,12);syncDiplomacy();render();toast('Agreement withdrawn. New talks are locked for 12 months.');}
function tickDiplomacy(){const expired=S.agreements.filter(p=>p.expires<=S.month);S.agreements=S.agreements.filter(p=>p.expires>S.month);for(const p of expired)if([p.a,p.b].includes(S.player))addEvent('Agreement expired',DIPLOMACY[p.type].name+' with '+nation(p.a===S.player?p.b:p.a).name+' is ready for renewal.','diplomacy');for(const p of S.agreements){if(p.type==='embassy'&&!S.sanctions.includes(pair(p.a,p.b)))setRelation(p.a,p.b,relation(p.a,p.b)+.15);if(p.type==='nonaggression')for(const id of [p.a,p.b])nation(id).stability=clamp(nation(id).stability+.025,0,100);}for(const[k,until]of Object.entries(S.diplomaticCooldowns))if(until<=S.month)delete S.diplomaticCooldowns[k];syncDiplomacy();if(S.options.ai&&S.month%6===0){const pool=S.nations.filter(n=>n.id!==S.player&&!n.war);if(pool.length>1){const a=pool[Math.floor(random()*pool.length)],b=pool[Math.floor(random()*pool.length)];if(a.id!==b.id&&!S.sanctions.includes(pair(a.id,b.id))){setRelation(a.id,b.id,relation(a.id,b.id)+3);if(relation(a.id,b.id)>25&&!agreement(a.id,b.id,'trade')&&Math.min(a.policies.trade,b.policies.trade)>=40)S.agreements.push({a:a.id,b:b.id,type:'trade',expires:S.month+60});}}}syncDiplomacy();}
const v3DeclareWar=declareWar;
declareWar=function(){const a=player(),b=current();if(agreement(a.id,b.id,'nonaggression')||agreement(a.id,b.id,'defense')){toast('Withdraw your non-aggression or defense agreement before declaring war.');return;}v3DeclareWar();if(a.war?.target===b.id){S.agreements=S.agreements.filter(p=>pair(p.a,p.b)!==pair(a.id,b.id));a.reputation=clamp(a.reputation-15,0,100);syncDiplomacy();}};
function tickV4Nation(n){tickCities(n);tickPolitics(n);n.human=clamp(n.human+n.policies.research*.006+n.pactResearch,0,100);n.clean=clamp(n.clean+n.pactClimate,0,100);n.capacity=clamp(n.capacity+(n.policies.antiCorruption-n.capacity)*.0007,0,100);n.readiness=clamp(n.readiness+n.pactDefense*.01,20,95);n.pop*=1+(n.policies.immigration-50)*.00001;n.rentBurden=clamp(n.rentBurden+Math.max(0,n.policies.immigration-50)*.0008,8,65);n.unemployment=clamp(n.unemployment+Math.max(0,n.policies.minimumWage-70)*.001,2,28);n.inequality=clamp(n.inequality-n.policies.pension*.01-(n.policies.minimumWage-45)*.0003,5,75);}
const v3Fiscal=fiscal;
fiscal=function(n,p=n.policies){const b=v3Fiscal(n,p),forgiving=S?.options?.forgivingDebt!==false,ratio=n.debt/n.gdp*100,interest=forgiving?clamp(p.rate*.35+.65+Math.max(0,ratio-180)*.006-n.capacity*.007-p.borrowing*.009,.2,5):b.interest,newPrograms=p.research+p.pension+p.foodSecurity+p.antiCorruption*.006+p.decentralization*.003+(n.citySpend||0)+(n.cityUpkeep||0);b.spending+=newPrograms;b.interest=interest;b.debtService=n.debt/n.gdp*interest;b.balance=b.revenue-b.spending-b.debtService;b.newPrograms=newPrograms;return b;};
function handleDebtV4(n){if(n.crisisGrace>0)n.crisisGrace--;const threshold=S.options.forgivingDebt?6:4.5;if(n.debt/n.gdp>3.5&&!n.debtWarned){n.debtWarned=1;if(n.id===S.player)addEvent('Debt review recommended','Debt exceeds 350% of output. Voluntary relief is available; no immediate default penalty applies.','economy');}if(n.debt/n.gdp<3)n.debtWarned=0;n.crisisMonths=n.debt/n.gdp>threshold?n.crisisMonths+1:0;if(n.crisisMonths>=12&&n.crisisGrace===0){n.debt*=.75;n.growth-=.5;n.stability=clamp(n.stability-2,0,100);n.crisisGrace=48;n.crisisMonths=0;if(n.id===S.player)addEvent('Managed debt workout','After twelve months above the intervention threshold, creditors agreed to a 25% write-down. Repeat intervention is suspended for four years.','economy');}}
const v3DebtRelief=debtRelief;
debtRelief=function(kind){const n=player(),before=n.reliefCooldown;const approval=n.approval,growth=n.growth;v3DebtRelief(kind);if(n.reliefCooldown>before){n.crisisGrace=36;n.crisisMonths=0;if(kind==='restructure'){n.approval=clamp(approval-3,5,95);n.growth=growth-.4;}render();}};
const v3ReformCost=reformCost;
reformCost=function(n,values){const cost=v3ReformCost(n,values);return Math.ceil(cost*(n.policies.institutions>=60?(coalitionSeats(n)>50?.85:1.15):1));};

function citiesPanel(n){if(activeCity>=n.cities.length)activeCity=0;const c=n.cities[activeCity],m=cityMetrics(n,c),owned=n.id===S.player;return '<h3>City development</h3><p>Choose a city and finance individual projects. Two construction slots per city; five levels per development.</p><div class="citypicker">'+n.cities.map((x,i)=>'<button class="'+(i===activeCity?'primary':'')+'" data-city="'+i+'">'+escapeHTML(x.name)+'</button>').join('')+'</div><div class="ideologybox"><div class="eyebrow">'+(CITY_NAMES[n.id]?'Named city · illustrative municipal model':'Generated district · sandbox model')+'</div><strong>'+escapeHTML(c.name)+'</strong>'+metric('Modeled local output',money(n.gdp*c.share))+'<p>These cities represent 50% of national output in the scenario. Remaining regions are simulated nationally; municipal shares and all local indicators are invented for gameplay.</p></div><div class="previewgrid">'+Object.entries(m).map(([k,v])=>'<div class="minicard"><label>'+k[0].toUpperCase()+k.slice(1)+'</label><strong>'+v.toFixed(0)+'<small style="font-size:12px"> /100</small></strong></div>').join('')+'</div><h3>Construction queue · '+c.queue.length+'/2</h3>'+(c.queue.length?c.queue.map((q,i)=>'<div class="projectcard"><strong>'+PROJECTS[q.type].name+'</strong>'+metric('Time remaining',q.remaining+' months')+progressBar((1-q.remaining/q.duration)*100)+metric('Remaining finance',money(q.cost*q.remaining/q.duration))+(owned?'<button data-cancel-city="'+c.id+'" data-cancel-index="'+i+'">Cancel remaining work</button>':'')+'</div>').join(''):'<p>No projects under construction.</p>')+'<h3>Start a development</h3>'+Object.entries(PROJECTS).map(([k,p])=>'<div class="projectcard"><div class="sectionhead"><strong>'+p.name+'</strong><span class="eyebrow">LV '+c.levels[k]+'/5</span></div><p>'+p.desc+'</p>'+metric('Total finance',money(n.gdp*c.share*p.cost/100))+metric('Construction',Math.max(6,Math.ceil(p.months*(1.1-n.policies.decentralization*.002)))+' months')+'<button class="full" data-build="'+k+'" '+(!owned||!canSpend(n,6)||c.queue.length>=2||c.levels[k]+c.queue.filter(q=>q.type===k).length>=5?'disabled':'')+'>Approve · 6 political capital</button></div>').join('')+'<p class="note">Construction is paid monthly, with no up-front double charge. Finished projects have recurring upkeep. Cancelling stops future payments without refunding past work.</p>';}
function partiesPanel(n){const p=n.politics,own=n.id===S.player;return '<h3>Parties & governing coalition</h3><p>Fictional parties represent competing platforms. Popularity changes monthly; seats change at elections.</p><div class="ideologybox"><div class="eyebrow">Governing party</div><strong>'+PARTY_DEFS[p.leader].name+'</strong>'+metric('Coalition strength',coalitionSeats(n)+' / 100 seats')+metric('Government status',coalitionSeats(n)>50?'Majority':'Minority')+metric('Next election',n.policies.institutions>=60?n.election+' months':'No competitive election cycle')+'</div><div class="seatbar" aria-label="Assembly seats">'+PARTY_DEFS.map((d,i)=>'<div title="'+d.name+': '+p.seats[i]+' seats" style="width:'+p.seats[i]+'%;background:'+d.color+'"></div>').join('')+'</div><p>Majorities reduce reform capital costs by 15%; minorities increase them by 15%. Parties with very distant platforms may decline coalition talks.</p>'+PARTY_DEFS.map((d,i)=>'<div class="projectcard"><strong style="color:'+d.color+'">'+d.name+'</strong><p>'+d.ideology+'</p>'+metric('Polling / seats',p.polls[i].toFixed(1)+'% / '+p.seats[i])+metric('Cabinet role',p.leader===i?'Leading party':p.coalition.includes(i)?'Coalition member':'Opposition')+(own?'<div class="buttonrow"><button data-party-action="campaign" data-party="'+i+'" '+(p.campaignCooldown||!canSpend(n,8)?'disabled':'')+'>Campaign · 8</button>'+(p.leader!==i?'<button data-party-action="coalition" data-party="'+i+'">'+(p.coalition.includes(i)?'Leave coalition':'Invite to coalition')+'</button>':'')+'</div>'+(p.leader!==i?'<button class="ghost full" data-party-action="lead" data-party="'+i+'">Lead this party · sandbox switch</button>':''):'')+'</div>').join('')+(own?'<button class="full" data-party-action="platform">Stage coalition platform</button><button class="full" data-party-action="election" '+(n.policies.institutions<60||p.snapCooldown||!canSpend(n,15)?'disabled':'')+'>Snap election · 15 capital</button>'+metric('Campaign cooldown',p.campaignCooldown+' months')+metric('Snap-election cooldown',p.snapCooldown+' months'):'')+'<p class="note">Party names, polls and seats are fictional. Leadership switches are sandbox actions. No country’s actual legislature is reproduced.</p>';}
diplomacyPanel=function(n){const a=player();if(n.id===a.id)return '<h3>Diplomatic service</h3>'+metric('International reputation',a.reputation.toFixed(0)+' / 100')+'<p>Each partner has separate relations, agreements, sanctions and negotiation cooldowns.</p><label class="eyebrow" for="partner">Choose a partner</label><select id="partner" class="full">'+S.nations.filter(b=>b.id!==a.id).sort((b,c)=>c.gdp-b.gdp).map(b=>'<option value="'+b.id+'">'+escapeHTML(b.name)+'</option>').join('')+'</select><button class="primary full" id="inspectPartner">Open diplomatic channel →</button><h3 style="margin-top:24px">Your agreements</h3>'+activeAgreementList(a);
return '<h3>Relations with '+escapeHTML(n.name)+'</h3>'+metric('Bilateral relations',relation(a.id,n.id).toFixed(0)+' / 100')+metric('Their reputation',n.reputation.toFixed(0)+' / 100')+metric('Their sanctions against you',S.embargoes.some(e=>e.from===n.id&&e.to===a.id)?'Active':'None')+'<p>Acceptance is rule-based. Requirements and cooldowns are visible before you spend capital.</p>'+Object.entries(DIPLOMACY).map(([k,d])=>{const pact=agreement(a.id,n.id,k),ownSanction=k==='sanction'&&S.embargoes.some(e=>e.from===a.id&&e.to===n.id),issue=diplomacyProblem(a,n,k);return '<div class="projectcard"><strong>'+d.name+'</strong><p>'+d.desc+(k==='aid'?' Current grant: '+money(Math.min(a.gdp*.002,n.gdp*.005))+'.':'')+'</p>'+(pact?metric('Agreement expires',pact.expires-S.month+' months')+'<button class="full" data-withdraw="'+k+'">Withdraw agreement · reputation −4</button>':'<p class="'+(issue?'neutral':'positive')+'">'+(issue||'Ready to proceed')+'</p><button class="full" data-diplomacy="'+k+'" '+(issue?'disabled':'')+'>'+(ownSanction?'Lift your sanctions':d.name+' · '+d.cost+' capital')+'</button>')+'</div>';}).join('')+(a.war?.target===n.id?'<button class="primary full" data-action="peace">Negotiate direct ceasefire</button>':'')+'<p class="note">Defensive cooperation improves readiness without automatic military intervention. Sanctions suspend economic benefits. Reputation affects the relation requirements of advanced agreements.</p>';};
function activeAgreementList(a){const list=S.agreements.filter(p=>[p.a,p.b].includes(a.id));return list.length?list.map(p=>'<div class="projectcard"><strong>'+DIPLOMACY[p.type].name+'</strong>'+metric(nation(p.a===a.id?p.b:p.a).name,(p.expires-S.month)+' months left')+'</div>').join(''):'<p>No agreements yet. Open a diplomatic channel to begin.</p>';}
const v3BindPanel=bindPanel;
bindPanel=function(){v3BindPanel();$('panel').querySelectorAll('[data-city]').forEach(b=>b.onclick=()=>{activeCity=Number(b.dataset.city);renderPanel();});$('panel').querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>startCityProject(current().id,current().cities[activeCity].id,b.dataset.build));$('panel').querySelectorAll('[data-cancel-city]').forEach(b=>b.onclick=()=>cancelCityProject(b.dataset.cancelCity,Number(b.dataset.cancelIndex)));$('panel').querySelectorAll('[data-party-action]').forEach(b=>b.onclick=()=>politicalAction(b.dataset.partyAction,Number(b.dataset.party)));$('panel').querySelectorAll('[data-withdraw]').forEach(b=>b.onclick=()=>withdrawPact(b.dataset.withdraw));};
const v3ProgramHeadline=programHeadline;
programHeadline=function(key,n){if(['governance','innovation','security'].includes(key))return ({governance:'Institutional capacity '+n.capacity.toFixed(0)+'/100',innovation:'Research '+n.policies.research.toFixed(1)+'% GDP · human capital '+n.human.toFixed(0),security:'Pension & food support '+(n.policies.pension+n.policies.foodSecurity).toFixed(1)+'% GDP'})[key];return v3ProgramHeadline(key,n);};
const v3ProgramStatus=programStatus;
programStatus=function(key,n){if(key==='debt'){const b=fiscal(n);return metric('Debt stock',money(n.debt))+metric('Debt / GDP',b.debtRatio.toFixed(1)+'%')+metric('Interest rate carried',b.interest.toFixed(2)+'%')+metric('Annual interest bill',b.debtService.toFixed(2)+'% GDP')+metric('Primary balance',pct(b.revenue-b.spending))+metric('Overall fiscal balance',pct(b.balance))+metric('Months above intervention threshold',n.crisisMonths+' / 12')+metric('Protection from repeat intervention',n.crisisGrace+' months')+'<p>'+(S.options.forgivingDebt?'Forgiving mode: interest capped at 5%, debt-ratio premiums begin above 180% GDP, and automatic relief requires twelve consecutive months above 600% GDP.':'Standard mode uses V3 carrying costs and a 450% GDP threshold, also with a twelve-month review.')+' After intervention, four years of protection prevent repeated monthly penalties.</p>';}
if(['governance','innovation','security'].includes(key))return PROGRAMS.find(p=>p.key===key).keys.map(k=>metric(POLICY.find(x=>x.key===k).name,n.policies[k].toFixed(1))).join('');return v3ProgramStatus(key,n);};
const v3EconomyPanel=economyPanel;
economyPanel=function(n){return '<div class="block"><h3>V4 development & debt</h3>'+metric('Municipal construction',(n.citySpend||0).toFixed(3)+'% GDP / year')+metric('Municipal upkeep',(n.cityUpkeep||0).toFixed(3)+'% GDP / year')+metric('Additional reform programs',(fiscal(n).newPrograms-(n.citySpend||0)-(n.cityUpkeep||0)).toFixed(2)+'% GDP')+metric('Debt rules',S.options.forgivingDebt?'Forgiving':'Standard')+'<p>City construction and new reforms are included in total spending and the deficit below. City commitments update at the next monthly budget.</p></div>'+v3EconomyPanel(n);};
const v3SettingsPanel=settingsPanel;
settingsPanel=function(){return '<h3>V4 debt rules</h3><label class="toggleline">Forgiving debt system<input type="checkbox" data-option="forgivingDebt" '+(S.options.forgivingDebt?'checked':'')+'></label><p>Lower carrying rates, a higher intervention threshold and protection from repeat debt crises.</p>'+v3SettingsPanel();};
const v3ShowGuide=showGuide;
showGuide=function(){v3ShowGuide();$('modalContent').insertAdjacentHTML('afterbegin','<div class="block"><h3>Sovereign V4</h3><p><b>Cities:</b> choose a named city, build housing, transit, hospitals, colleges, industry, clean energy, water networks and broadband. Construction is financed monthly and completed projects need upkeep.</p><p><b>Parties:</b> eight fictional parties compete for a 100-seat assembly. Build coalitions, campaign, hold elections and stage a coalition platform. The 14 ideology presets are editable tendencies, independent of democratic institutions.</p><p><b>Diplomacy:</b> embassies, specialized agreements, aid, summits, mediation and directional sanctions now have separate rules, durations and cooldowns. Withdrawal lowers reputation. No real-world treaties or wars are preloaded.</p><p><b>Debt:</b> forgiving mode caps interest at 5%, starts risk premiums above 180% GDP, and waits for twelve consecutive months above 600% GDP before a managed workout. A four-year protection period prevents repeated intervention. These are deliberately generous game rules, not real lending terms.</p><p>V1–V3 saves migrate on import. Municipal names are real for featured nations; local statistics, population shares and all political parties are scenario constructs. Elsewhere, cities are explicitly generated districts.</p></div>');};
function migrateV4(s){if(s?.version!==3)return s;s.version=4;s.options.forgivingDebt=true;s.agreements=(s.treaties||[]).map(key=>{const[a,b]=key.split(':');return{a,b,type:'trade',expires:s.month+60};});s.embargoes=(s.sanctions||[]).map(key=>{const ids=key.split(':');return{from:ids.includes(s.player)?s.player:ids[0],to:ids.includes(s.player)?ids.find(id=>id!==s.player):ids[1]};});s.diplomaticCooldowns={};for(const n of s.nations)ensureV4(n);return s;}
const v3MigrateSave=migrateSave;
migrateSave=function(s){return migrateV4(v3MigrateSave(s));};
const legacyValidSave=validSave;
validSave=function(s){legacyValidSave(s);if(typeof s.options.forgivingDebt!=='boolean'||!Array.isArray(s.agreements)||s.agreements.length>3000||!Array.isArray(s.embargoes)||s.embargoes.length>3000||!s.diplomaticCooldowns||typeof s.diplomaticCooldowns!=='object'||Array.isArray(s.diplomaticCooldowns))throw Error('Invalid V4 diplomatic state.');const ids=new Set(s.nations.map(n=>n.id)),keys=new Set();for(const p of s.agreements){const key=p.type+':'+pair(p.a,p.b);if(!PACT_TYPES.includes(p.type)||!ids.has(p.a)||!ids.has(p.b)||p.a===p.b||!Number.isInteger(p.expires)||p.expires<s.month||p.expires>s.month+120||keys.has(key))throw Error('Invalid agreement.');keys.add(key);}keys.clear();for(const e of s.embargoes){const key=e.from+':'+e.to;if(!ids.has(e.from)||!ids.has(e.to)||e.from===e.to||keys.has(key))throw Error('Invalid sanctions.');keys.add(key);}for(const[k,v]of Object.entries(s.diplomaticCooldowns)){const parts=k.split(':');if(parts.length!==3||!ids.has(parts[0])||!ids.has(parts[1])||!DIPLOMACY[parts[2]]||!Number.isInteger(v)||v<0||v>s.month+120)throw Error('Invalid diplomatic cooldown.');}
for(const n of s.nations){for(const k of ['reputation','crisisMonths','crisisGrace','citySpend','cityUpkeep','cityGrowth','pactGrowth','pactResearch','pactClimate','pactDefense'])if(!Number.isFinite(n[k])||n[k]<0||n[k]>10000)throw Error('Invalid V4 nation state.');if(n.reputation>100||n.crisisGrace>48)throw Error('Invalid reputation or debt protection.');const defaults=v4Cities(n);if(!Array.isArray(n.cities)||n.cities.length!==3)throw Error('Invalid cities.');for(let i=0;i<3;i++){const c=n.cities[i],d=defaults[i];if(c.id!==d.id||c.name!==d.name||c.share!==d.share||!c.levels||Object.keys(c.levels).length!==Object.keys(PROJECTS).length||Object.keys(c.levels).some(k=>!PROJECTS[k])||!Array.isArray(c.queue)||c.queue.length>2)throw Error('Invalid city.');for(const k of Object.keys(PROJECTS))if(!Number.isInteger(c.levels[k])||c.levels[k]<0||c.levels[k]>5)throw Error('Invalid development level.');for(const q of c.queue)if(!PROJECTS[q.type]||!Number.isInteger(q.duration)||q.duration<6||q.duration>40||!Number.isInteger(q.remaining)||q.remaining<1||q.remaining>q.duration||!Number.isFinite(q.cost)||q.cost<=0||q.cost>1e14||c.levels[q.type]+c.queue.filter(x=>x.type===q.type).length>5)throw Error('Invalid construction queue.');}const p=n.politics;if(!p||!Array.isArray(p.polls)||p.polls.length!==8||p.polls.some(v=>!Number.isFinite(v)||v<0||v>100)||Math.abs(p.polls.reduce((a,b)=>a+b,0)-100)>.01||!Array.isArray(p.seats)||p.seats.length!==8||p.seats.some(v=>!Number.isInteger(v)||v<0)||p.seats.reduce((a,b)=>a+b,0)!==100||!Number.isInteger(p.leader)||!PARTY_DEFS[p.leader]||!Array.isArray(p.coalition)||new Set(p.coalition).size!==p.coalition.length||p.coalition.some(i=>!Number.isInteger(i)||!PARTY_DEFS[i])||!p.coalition.includes(p.leader)||!Array.isArray(p.boost)||p.boost.length!==8||p.boost.some(v=>!Number.isFinite(v)||v<0||v>100))throw Error('Invalid political system.');for(const k of ['campaignCooldown','snapCooldown'])if(!Number.isInteger(p[k])||p[k]<0||p[k]>48)throw Error('Invalid election cooldown.');for(const k of ['tax','welfare','ownership','labor','trade','climate']){const rule=POLICY.find(x=>x.key===k);if(!Number.isFinite(p.preference?.[k])||p.preference[k]<rule.min||p.preference[k]>rule.max)throw Error('Invalid electorate preferences.');}}
const expectedTrade=[...new Set(s.agreements.filter(p=>p.type==='trade').map(p=>pair(p.a,p.b)))].sort(),expectedSanctions=[...new Set(s.embargoes.map(e=>pair(e.from,e.to)))].sort();if(JSON.stringify([...s.treaties].sort())!==JSON.stringify(expectedTrade)||JSON.stringify([...s.sanctions].sort())!==JSON.stringify(expectedSanctions))throw Error('Inconsistent agreement indexes.');return s;};
